Deprecate null-ls in favor of conform and lspconfig

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -141,13 +141,13 @@ alias egrep='egrep --color=auto'
 
 # Add an "alert" function for long running commands.  Use like so:
 # alert sleep 10
-alert() {
-  set +e  # Disable immediate exit on error
-  gum spin --spinner dot --title "Running $*..." --show-output -- "$@"
-  ret_code=$?
-  notify-send --urgency=low "$* done"
-  return $ret_code
-}
+# alert() {
+#   set +e  # Disable immediate exit on error
+#   gum spin --spinner dot --title "Running $*..." --show-output -- "$@"
+#   ret_code=$?
+#   notify-send --urgency=low "$* done"
+#   return $ret_code
+# }
 
 # Count lines of code in a git repo
 gloc() {
@@ -219,3 +219,7 @@ eval "$(fzf --zsh)"
 export PYENV_ROOT="$HOME/.pyenv"
 [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
 eval "$(pyenv init - zsh)"
+export PATH="/usr/local/opt/tcl-tk/bin:$PATH"
+
+# Add local bin to PATH for pipx
+export PATH="$PATH:~/.local/bin"
